/*
  Warnings:

  - The values [PRE_TICKETING_OPEN,GENERAL_TICKETING_OPEN] on the enum `notification_dispatch_type` will be removed. If these variants are still used in the database, this will fail.
  - The values [PRE_TICKETING_OPEN,GENERAL_TICKETING_OPEN] on the enum `notification_dispatch_type` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `notification_dispatch` MODIFY `type` ENUM('INTEREST_CONCERT', 'PRE_TICKETING_10MIN', 'GENERAL_TICKETING_10MIN', 'PRE_TICKETING_1D', 'GENERAL_TICKETING_1D', 'PRE_TICKETING_30MIN', 'GENERAL_TICKETING_30MIN', 'CONCERT_INFO_UPDATE_SETLIST', 'CONCERT_INFO_UPDATE_MD', 'CONCERT_INFO_UPDATE_DETAIL', 'CONCERT_INFO_UPDATE_SCHEDULE', 'CONCERT_INFO_UPDATE_TICKET', 'ARTIST_CONCERT_OPEN', 'RECOMMEND', 'ADD_TICKETING_1D', 'ADD_TICKETING_30MIN', 'ADD_TICKETING_10MIN') NOT NULL;

-- AlterTable
ALTER TABLE `notificationhistories` MODIFY `type` ENUM('INTEREST_CONCERT', 'PRE_TICKETING_10MIN', 'GENERAL_TICKETING_10MIN', 'PRE_TICKETING_1D', 'GENERAL_TICKETING_1D', 'PRE_TICKETING_30MIN', 'GENERAL_TICKETING_30MIN', 'CONCERT_INFO_UPDATE_SETLIST', 'CONCERT_INFO_UPDATE_MD', 'CONCERT_INFO_UPDATE_DETAIL', 'CONCERT_INFO_UPDATE_SCHEDULE', 'CONCERT_INFO_UPDATE_TICKET', 'ARTIST_CONCERT_OPEN', 'RECOMMEND', 'ADD_TICKETING_1D', 'ADD_TICKETING_30MIN', 'ADD_TICKETING_10MIN') NOT NULL;

-- AlterTable
ALTER TABLE `schedule` MODIFY `type` ENUM('CONCERT', 'PRE_TICKETING', 'GENERAL_TICKETING', 'ADD_TICKETING') NULL;
