export enum ConcertGenre {
  ALL = 'ALL',
  JPOP = 'JPOP',
  ROCK_METAL = 'ROCK_METAL',
  RAP_HIPHOP = 'RAP_HIPHOP',
  CLASSIC_JAZZ = 'CLASSIC_JAZZ',
  ACOUSTIC = 'ACOUSTIC',
  ELECTRONIC = 'ELECTRONIC',
}
