name: deploy

on:
  push:
    branches:
      - develop
      - main
      - legacy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prisma has changes
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Set deploy variables
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "TARGET=dev_livith_ec2" >> $GITHUB_ENV
            echo "APP_DIR=/opt/app" >> $GITHUB_ENV
            echo "SERVICE=app" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/legacy" ]]; then
            echo "TARGET=livith_ec2" >> $GITHUB_ENV
            echo "APP_DIR=/opt/app-legacy" >> $GITHUB_ENV
            echo "SERVICE=app-legacy" >> $GITHUB_ENV
          else
            echo "TARGET=livith_ec2" >> $GITHUB_ENV
            echo "APP_DIR=/opt/app" >> $GITHUB_ENV
            echo "SERVICE=app" >> $GITHUB_ENV
          fi

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          cat <<EOF > ~/.ssh/config
          Host dev_livith_ec2
            HostName $DEV_EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
          else
          cat <<EOF > ~/.ssh/config
          Host livith_ec2
            HostName $PROD_EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
          fi
        env:
          EC2_USER: ubuntu
          DEV_EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
          PROD_EC2_HOST: ${{ secrets.PROD_EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh ${{ env.TARGET }} "sudo mkdir -p ${{ env.APP_DIR }}"
          ssh ${{ env.TARGET }} "sudo chown ubuntu:ubuntu ${{ env.APP_DIR }}"
          rsync -av ./ ${{ env.TARGET }}:${{ env.APP_DIR }}

      - name: Install dependencies
        run: |
          ssh ${{ env.TARGET }} "npm install --prefix ${{ env.APP_DIR }}/"
          ssh ${{ env.TARGET }} "cd ${{ env.APP_DIR }}; npm exec prisma generate"

      - name: Build project
        run: |
          ssh ${{ env.TARGET }} "cd ${{ env.APP_DIR }}; npm run build"

      - name: Apply prisma migrations
        if: steps.paths-filter.outputs.prisma == 'true'
        run: |
          ssh ${{ env.TARGET }} "cd ${{ env.APP_DIR }}; npm exec prisma migrate deploy"

      - name: Copy systemd service file
        run: |
          APP_DIR="${{ env.APP_DIR }}"
          SERVICE="${{ env.SERVICE }}"
          ssh ${{ env.TARGET }} "sudo tee /etc/systemd/system/${SERVICE}.service" << EOF
          [Unit]
          Description=Livith Project
          After=network.target

          [Service]
          User=ubuntu
          ExecStart=/usr/bin/npm run start:prod --prefix ${APP_DIR}/
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOF

      - name: Enable systemd service
        run: |
          ssh ${{ env.TARGET }} 'sudo systemctl daemon-reload'
          ssh ${{ env.TARGET }} "sudo systemctl enable ${{ env.SERVICE }}"

      - name: Restart systemd service
        run: |
          ssh ${{ env.TARGET }} "sudo systemctl restart ${{ env.SERVICE }}"
