-- CreateTable
CREATE TABLE `notification_dispatch` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `schedule_id` INTEGER NOT NULL,
    `type` ENUM('INTEREST_CONCERT', 'PRE_TICKETING_OPEN', 'GENERAL_TICKETING_OPEN', 'PRE_TICKETING_1D', 'GENERAL_TICKETING_1D', 'PRE_TICKETING_30MIN', 'GENERAL_TICKETING_30MIN', 'CONCERT_INFO_UPDATE_SETLIST', 'CONCERT_INFO_UPDATE_MD', 'CONCERT_INFO_UPDATE_DETAIL', 'CONCERT_INFO_UPDATE_SCHEDULE', 'CONCERT_INFO_UPDATE_TICKET', 'ARTIST_CONCERT_OPEN', 'RECOMMEND') NOT NULL,
    `status` ENUM('SENDING', 'SENT', 'FAILED') NOT NULL DEFAULT 'SENDING',
    `claimed_by` VARCHAR(100) NULL,
    `claimed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `completed_at` DATETIME(3) NULL,

    UNIQUE INDEX `notification_dispatch_schedule_id_type_key`(`schedule_id`, `type`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
